name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: spacemeowx2/devkitpro-action@v2
        with:
          libnx-rev: 5ca15e7696e174c41ee94974d62602fde722ac3b
          cmd: make -j8

      - name: Upload built files
        uses: actions/upload-artifact@v1
        with:
          name: sdcard
          path: out/sd

      - name: Upload elf file
        uses: actions/upload-artifact@v1
        with:
          name: ldn_mitm.elf
          path: ldn_mitm/ldn_mitm.elf

      - name: Upload elf file
        uses: actions/upload-artifact@v1
        with:
          name: ldn_mitm.elf
          path: overlay/overlay.elf
